Add LabelsToTagsMap and EnsureStringArray functions to sdk plugin. closes #3
turbot/steampipe-plugin-sdk pull request #4
Opened 2021-01-20 16:59 UTC by tyagiparth

2021-01-22 09:18 UTC, kaidaguerre commented on plugin/transform/primitives.go
> +		return nil, errors.New("ERROR")
```
return nil, fmt.errorf("LabelsToTagsMap transform requires the input to be []string, got %s", reflect.Typeof(d.Value).Name)
```

2021-01-27 12:32 UTC, e-gineer commented
What name are we using for this function? Maybe it should be StringArrayToMap?

2021-01-27 14:00 UTC, kaidaguerre commented
yup that's the question. `StringArrayToMap` is good

2021-01-27 14:01 UTC, kaidaguerre requested changes

2021-01-27 14:01 UTC, kaidaguerre commented on plugin/transform/primitives.go
> +func LabelsToTagsMap(_ context.Context, d *TransformData) (interface{}, error) {
rename to StringArrayToMap

2021-01-29 10:33 UTC, merged