Added concurrency function in SDK
turbot/steampipe-plugin-sdk pull request #8
Opened 2021-01-29 11:53 UTC by tyagiparth

2021-02-01 15:27 UTC, tyagiparth commented on plugin/hydrate.go
> +	return concurrencyManager.StartIfAllowed(name, h.Config.MaxConcurrency)
yes, we are handling this here https://github.com/turbot/steampipe-plugin-sdk/pull/8/files#diff-51a868288d020cff3c5bb36badb8b720248be74cc791cf30fc7171086f949913R38

2021-02-02 08:56 UTC, kaidaguerre requested changes

2021-02-02 08:56 UTC, kaidaguerre commented on plugin/hydrate.go
> +// HydrateDependencies :: define the hydrate function dependencies - other hydrate functions which must be run first
change comment

2021-02-02 08:56 UTC, kaidaguerre commented on plugin/hydrate.go
> +type DefaultHydrateConfig struct {
add a comment - explain this is used by the plugin

2021-02-02 08:56 UTC, kaidaguerre commented on plugin/concurrency.go
> +func newConcurrencyManager() *ConcurrencyManager {
for now remove (comment out) `defaultMaxPerCall` - our config schema does not include it

We need to move defaultMaxCalls into the concurrency manager and populate from the plugin  `DefaultHydrateConfig.MaxConcurrency` (add same var to `ConcurrencyManmager` )

callMaxMap either needs to be populated when we start concurrency manager from the hydrate configs of the required hydrate functions, or removed and use the hydrate config directly

2021-02-05 11:45 UTC, kaidaguerre approved these changes

2021-02-05 11:45 UTC, merged